### ISSUE TITLE
Crash when I open the reset table. Logs included.

### ISSUE THREAD

**Issue by IdontPlayz343** [takusan23/ResetTable#1]
---- Minecraft Crash Report ----
// Hi. I'm Minecraft, and I'm a crashaholic.

Time: 09/07/2022, 9:22 pm
Description: Rendering screen

java.lang.NullPointerException: Cannot invoke "net.minecraft.class_1799.method_7909()" because the return value of "net.minecraft.class_1860.method_8110()" is null
	at io.github.takusan23.resettable.tool.ResetTableTool.findRecipe(ResetTableTool.kt:61)
	at io.github.takusan23.resettable.tool.ResetTableTool.verifyResultItemRecipe(ResetTableTool.kt:74)
	at io.github.takusan23.resettable.screen.ResetTableScreenHandler.verifyResultItem(ResetTableScreenHandler.kt:106)
	at io.github.takusan23.resettable.screen.ResetTableScreen.method_2388(ResetTableScreen.kt:44)
	at net.minecraft.class_465.method_25394(class_465.java:134)
	at io.github.takusan23.resettable.screen.ResetTableScreen.method_25394(ResetTableScreen.kt:61)
	at net.minecraft.class_757.method_3192(class_757.java:881)
	at net.minecraft.class_310.method_1523(class_310.java:1143)
	at net.minecraft.class_310.method_1514(class_310.java:734)
	at net.minecraft.client.main.Main.main(Main.java:237)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at io.github.takusan23.resettable.tool.ResetTableTool.findRecipe(ResetTableTool.kt:61)
	at io.github.takusan23.resettable.tool.ResetTableTool.verifyResultItemRecipe(ResetTableTool.kt:74)
	at io.github.takusan23.resettable.screen.ResetTableScreenHandler.verifyResultItem(ResetTableScreenHandler.kt:106)
	at io.github.takusan23.resettable.screen.ResetTableScreen.method_2388(ResetTableScreen.kt:44)
	at net.minecraft.class_465.method_25394(class_465.java:134)
	at io.github.takusan23.resettable.screen.ResetTableScreen.method_25394(ResetTableScreen.kt:61)

-- Screen render details --
Details:
	Screen name: io.github.takusan23.resettable.screen.ResetTableScreen
	Mouse location: Scaled: (480, 270). Absolute: (960.000000, 540.000000)
	Screen size: Scaled: (960, 540). Absolute: (1920, 1080). Scale factor of 2.000000
Stacktrace:
	at net.minecraft.class_757.method_3192(class_757.java:881)
	at net.minecraft.class_310.method_1523(class_310.java:1143)
	at net.minecraft.class_310.method_1514(class_310.java:734)
	at net.minecraft.client.main.Main.main(Main.java:237)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

-- Affected level --
Details:
	All players: 1 total; [class_746['MelonSlayer78'/31, l='ClientLevel', x=1972.16, y=113.77, z=-326.61]]
	Chunk stats: 1024, 646
	Level dimension: minecraft:overworld
	Level spawn location: World: (16,82,-128), Section: (at 0,2,0 in 1,5,-8; chunk contains blocks 16,-64,-128 to 31,319,-113), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,-64,-512 to 511,319,-1)
	Level time: 344492 game time, 312564 day time
	Server brand: fabric
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.class_638.method_8538(class_638.java:453)
	at net.minecraft.class_310.method_1587(class_310.java:2288)
	at net.minecraft.class_310.method_1514(class_310.java:753)
	at net.minecraft.client.main.Main.main(Main.java:237)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:461)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:210)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:245)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

-- Last reload --
Details:
	Reload number: 2
	Reload reason: manual
	Finished: Yes
	Packs: Default, Fabric Mods, visualoverhaul/coloredwaterbucket, visualoverhaul/nobrewingbottles, visualoverhaul/fancyfurnace, visualoverhaul/rounddiscs, better-rain-1-17, Theinar Language, cullleaves/smartleaves

-- System Details --
Details:
	Minecraft Version: 1.19
	Minecraft Version ID: 1.19
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.3, Eclipse Adoptium
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode, sharing), Eclipse Adoptium
	Memory: 1891690216 bytes (1804 MiB) / 3999268864 bytes (3814 MiB) up to 3999268864 bytes (3814 MiB)
	CPUs: 8
	Processor Vendor: AuthenticAMD
	Processor Name: AMD Ryzen 5 1500X Quad-Core Processor          
	Identifier: AuthenticAMD Family 23 Model 1 Stepping 1
	Microarchitecture: unknown
	Frequency (GHz): 3.49
	Number of physical packages: 1
	Number of physical CPUs: 4
	Number of logical CPUs: 8
	Graphics card #0 name: NVIDIA GeForce GTX 1080
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x1b80
	Graphics card #0 versionInfo: DriverVersion=31.0.15.1659
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 2.13
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 2.13
	Memory slot #1 type: DDR4
	Memory slot #2 capacity (MB): 8192.00
	Memory slot #2 clockSpeed (GHz): 2.13
	Memory slot #2 type: DDR4
	Memory slot #3 capacity (MB): 8192.00
	Memory slot #3 clockSpeed (GHz): 2.13
	Memory slot #3 type: DDR4
	Virtual memory max (MB): 46513.68
	Virtual memory used (MB): 41530.34
	Swap memory total (MB): 13794.18
	Swap memory used (MB): 388.60
	JVM Flags: 3 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms512m -Xmx3814m
	Fabric Mods: 
		additionaladditions: Additional Additions 5.0.1
		advancedcombat: Advanced Combat 1.0-SNAPSHOT
		advancementplaques: Advancement Plaques 1.4.5
		ae2: Applied Energistics 2 12.0.0-alpha
			noindium: No Indium? 1.0.2+1.18.2
				omega-config: OmegaConfig 1.2.3-1.18.1
		agape_space: Space Dimensions 0.5.16
		alternate-current: Alternate Current 1.4.0
		ambientsounds: Ambiend Sounds (Fabric) 5.2.0
		appleskin: AppleSkin 2.4.0+mc1.19
		architectury: Architectury 5.7.28
		attributefix: AttributeFix 15.0.1
		automated_crafting: Automated Crafting 1.4.5
			crowdin-translate: CrowdinTranslate 1.4+1.19
			libgui: LibGui 6.0.0+1.19
				jankson: Jankson 4.1.1+j1.2.1
				libninepatch: LibNinePatch 1.1.0
		autosmeltenchant: AutosmeltEnchant 1.1.0
		bclib: BCLib 2.0.10
		betterend: Better End 2.0.5
		bitsandchisels: BitsAndChisels 2.7.0
			stacc: Stacc 1.3.4
		bookshelf: Bookshelf 14.0.3
		bowinfinityfix: Bow Infinity Fix 2.5.0
		brb: Better Recipe Book 1.6.0
		castle_dungeons: Castle Dungeons 3.3-1.19-fabric
		chunky: Chunky 1.2.217
		cleancut: CleanCut 1.19-5.0-fabric
		cloth-config: Cloth Config v6 7.0.72
			cloth-basic-math: cloth-basic-math 0.6.1
		comforts: Comforts 6.0.0-beta.2+1.19
			cardinal-components-base: Cardinal Components API (base) 5.0.0-beta.1
			cardinal-components-entity: Cardinal Components API (entities) 5.0.0-beta.1
			spectrelib: SpectreLib 0.4.0+1.19
		conjuring: Conjuring 1.0.23+1.19
		couplings: Couplings 1.9.0+1.19
			com_electronwill_night-config_core: core 3.6.5
			com_electronwill_night-config_toml: toml 3.6.5
			fabric-api-base: Fabric API Base 0.4.9+e62f51a3a9
			fabric-networking-api-v1: Fabric Networking API (v1) 1.0.27+7fe97409a9
		creativecore: CreativeCore (Fabric) 2.7.2
		cullleaves: Cull Leaves 2.3.4
			midnightlib: MidnightLib 0.5.2
		darkutils: DarkUtilities 11.0.1
		dawn: Dawn API 3.5.0
		diggusmaximus: Diggus Maximus 1.5.6-1.19
			kyrptconfig: Kyrpt Config 1.4.6-1.19
				blue_endless_jankson: jankson 1.2.1
		disable_custom_worlds_advice: Disable Custom Worlds Advice 3.0
		disenchanter: Disenchanter 0.1.7+1.19
		dispenser_configurator: Dispenser Configurator 1.2.3
		eatinganimationid: Eating Animation 1.8.1
		enchant_the_rainbow: Enchant the Rainbow 1.1.0
		enchantmentcompat: Enchantment Compatibility 1.0.0
			roundalib: RoundaLib 0.1.8
		enderscape: Enderscape 0.3.4-1.19
		entityculling: EntityCulling-Fabric 1.5.2-mc1.19
			com_logisticscraft_occlusionculling: occlusionculling 0.0.6-SNAPSHOT
		equipmentcompare: Equipment Compare 1.3.1
		extremesoundmuffler: Extreme sound muffler 3.27_fabric-1.19
			fiber: fiber 0.23.0-2
		fabric: Fabric API 0.57.0+1.19
			fabric-api-lookup-api-v1: Fabric API Lookup API (v1) 1.6.7+9ff28f40a9
			fabric-biome-api-v1: Fabric Biome API (v1) 9.0.14+b2a4a624a9
			fabric-blockrenderlayer-v1: Fabric BlockRenderLayer Registration (v1) 1.1.18+9ff28f40a9
			fabric-command-api-v1: Fabric Command API (v1) 1.2.6+f71b366fa9
			fabric-command-api-v2: Fabric Command API (v2) 2.1.2+0d55f585a9
			fabric-commands-v0: Fabric Commands (v0) 0.2.23+df3654b3a9
			fabric-containers-v0: Fabric Containers (v0) 0.1.27+df3654b3a9
			fabric-content-registries-v0: Fabric Content Registries (v0) 3.2.0+07df213ea9
			fabric-convention-tags-v1: Fabric Convention Tags 1.0.8+37622d24a9
			fabric-crash-report-info-v1: Fabric Crash Report Info (v1) 0.2.3+bd0a0d4aa9
			fabric-data-generation-api-v1: Fabric Data Generation API (v1) 5.1.1+a680b9b4a9
			fabric-dimensions-v1: Fabric Dimensions API (v1) 2.1.28+a6d2f785a9
			fabric-entity-events-v1: Fabric Entity Events (v1) 1.4.16+9ff28f40a9
			fabric-events-interaction-v0: Fabric Events Interaction (v0) 0.4.26+9ff28f40a9
			fabric-events-lifecycle-v0: Fabric Events Lifecycle (v0) 0.2.25+df3654b3a9
			fabric-game-rule-api-v1: Fabric Game Rule API (v1) 1.0.19+18990361a9
			fabric-item-api-v1: Fabric Item API (v1) 1.5.4+767db26ea9
			fabric-item-groups-v0: Fabric Item Groups (v0) 0.3.25+9ff28f40a9
			fabric-key-binding-api-v1: Fabric Key Binding API (v1) 1.0.18+9ff28f40a9
			fabric-keybindings-v0: Fabric Key Bindings (v0) 0.2.16+df3654b3a9
			fabric-lifecycle-events-v1: Fabric Lifecycle Events (v1) 2.1.0+33fbc738a9
			fabric-loot-api-v2: Fabric Loot API (v2) 1.1.0+03a4e568a9
			fabric-loot-tables-v1: Fabric Loot Tables (v1) 1.1.3+9e7660c6a9
			fabric-message-api-v1: Fabric Message API (v1) 1.0.1+513f4a59a9
			fabric-mining-level-api-v1: Fabric Mining Level API (v1) 2.1.10+33fbc738a9
			fabric-models-v0: Fabric Models (v0) 0.3.15+9ff28f40a9
			fabric-networking-v0: Fabric Networking (v0) 0.3.14+df3654b3a9
			fabric-object-builder-api-v1: Fabric Object Builder API (v1) 4.0.7+9ff28f40a9
			fabric-particles-v1: Fabric Particles (v1) 1.0.8+dc39553aa9
			fabric-registry-sync-v0: Fabric Registry Sync (v0) 0.9.17+23c4cfefa9
			fabric-renderer-api-v1: Fabric Renderer API (v1) 1.0.8+9ff28f40a9
			fabric-renderer-indigo: Fabric Renderer - Indigo 0.6.9+1f92344ea9
			fabric-renderer-registries-v1: Fabric Renderer Registries (v1) 3.2.18+df3654b3a9
			fabric-rendering-data-attachment-v1: Fabric Rendering Data Attachment (v1) 0.3.12+9ff28f40a9
			fabric-rendering-fluids-v1: Fabric Rendering Fluids (v1) 3.0.5+9ff28f40a9
			fabric-rendering-v0: Fabric Rendering (v0) 1.1.20+df3654b3a9
			fabric-rendering-v1: Fabric Rendering (v1) 1.10.14+9ff28f40a9
			fabric-resource-conditions-api-v1: Fabric Resource Conditions API (v1) 2.0.9+e62f51a3a9
			fabric-resource-loader-v0: Fabric Resource Loader (v0) 0.5.5+a6d2f785a9
			fabric-screen-api-v1: Fabric Screen API (v1) 1.0.24+f05effafa9
			fabric-screen-handler-api-v1: Fabric Screen Handler API (v1) 1.2.6+9ff28f40a9
			fabric-textures-v0: Fabric Textures (v0) 1.0.18+9ff28f40a9
			fabric-transfer-api-v1: Fabric Transfer API (v1) 2.0.9+e62f51a3a9
			fabric-transitive-access-wideners-v1: Fabric Transitive Access Wideners (v1) 1.1.1+9e7660c6a9
		fabric-language-kotlin: Fabric Language Kotlin 1.8.1+kotlin.1.7.0
			org_jetbrains_kotlin_kotlin-reflect: kotlin-reflect 1.7.0
			org_jetbrains_kotlin_kotlin-stdlib: kotlin-stdlib 1.7.0
			org_jetbrains_kotlin_kotlin-stdlib-jdk7: kotlin-stdlib-jdk7 1.7.0
			org_jetbrains_kotlin_kotlin-stdlib-jdk8: kotlin-stdlib-jdk8 1.7.0
			org_jetbrains_kotlinx_atomicfu-jvm: atomicfu-jvm 0.18.0
			org_jetbrains_kotlinx_kotlinx-coroutines-core-jvm: kotlinx-coroutines-core-jvm 1.6.3
			org_jetbrains_kotlinx_kotlinx-coroutines-jdk8: kotlinx-coroutines-jdk8 1.6.3
			org_jetbrains_kotlinx_kotlinx-datetime-jvm: kotlinx-datetime-jvm 0.4.0
			org_jetbrains_kotlinx_kotlinx-serialization-cbor-jvm: kotlinx-serialization-cbor-jvm 1.3.3
			org_jetbrains_kotlinx_kotlinx-serialization-core-jvm: kotlinx-serialization-core-jvm 1.3.3
			org_jetbrains_kotlinx_kotlinx-serialization-json-jvm: kotlinx-serialization-json-jvm 1.3.3
		fabricloader: Fabric Loader 0.14.8
		fastload: Fast Load 1.1.5
		flytre_lib: FlytreLib 1.8.8
		forgeconfigapiport: Forge Config API Port 4.0.0
		forgetmechunk: Forget Me Chunk 1.0.4-1.18.X-1.19.X
		forgotten_features: Forgotten Features 1.5+1.19
		fpsdisplay: FPS-Display 1.5.0+1.19
		friendlyfire: FriendlyFire 12.0.1
		geckolib3: Geckolib 3.1.5
			com_eliotlash_mclib_mclib: mclib 18
			com_eliotlash_molang_molang: molang 18
		geodes: More Geodes 1.4.3
		hwg: Happiness is a Warm Gun 1.2.1
		iceberg: Iceberg 1.0.38
		indium: Indium 1.0.6+mc1.19
		iris: Iris 1.2.5
			org_anarres_jcpp: jcpp 1.4.14
		java: OpenJDK 64-Bit Server VM 17
		journeymap: Journeymap 5.8.5rc2
			journeymap-api-fabric: JourneyMap API 1.19-1.8-fabric-SNAPSHOT
		legendarytooltips: Legendary Tooltips 1.2.6
		lucky: Lucky Block 1.19-13.0
		maxhealthfix: MaxHealthFix 6.0.1
		mechanicaldispensers: MechanicalDispensers 4.0-1.19
		midashunger: Midas Hunger 2.1.0+1.19.0
		minecarttweaks: Cammie's Minecart Tweaks 1.6
		minecraft: Minecraft 1.19
		mining_dims: Mining Dimensions 1.4.17
			customportalapi: Custom Portal Api 0.0.1-beta51-1.19
			pugh_lib: Pugh Lib 1.4.8
		mobscarecrow: Mob Scarecrow 2.2.0
		modmenu: Mod Menu 4.0.0
		mousetweaks: Mouse Tweaks 2.22
		musicdr: Music Duration Reducer 2.1.0
		naturescompass: Nature's Compass 1.19-2.0.4-fabric
		no-shield-delay: No Shield Delay 1.0.0
		owo: oωo 0.7.3+1.19
		perfectaccuracy: Perfect Accuracy 1.2-1.19
		pipe: Pipe 1.8.3
		professions: Professions 0.2.2
			com_typesafe_config: config 1.4.1
			fabric-permissions-api-v0: fabric-permissions-api 0.1-SNAPSHOT
			io_leangen_geantyref_geantyref: geantyref 1.3.11
			octo-economy-api: Octo Economy API 1.0.1
			org_spongepowered_configurate-core: configurate-core 4.1.2
			org_spongepowered_configurate-hocon: configurate-hocon 4.1.2
		purpeille: Purpeille 3.0.0+fabric-1.19-hotfix
			cmods: Combined Modifiers 1.3.0+fabric-1.19
			voidcrafting: Void Crafting 1.7.1+fabric-1.19
		puzzle: Puzzle 1.3.3
			puzzle-base: Puzzle Base 1.3.3
			puzzle-gui: Puzzle GUI 1.3.3
			puzzle-models: Puzzle Models 1.3.3
			puzzle-splashscreen: Puzzle Splash Screen 1.3.3
		quartzelv: Quartz Elevator 2.1.3+1.19
		redstonebits: Redstone Bits 1.8.2
		resettable: ResetTable 1.0.0
		retraining: Retraining 1.2.0
		ring_of_attraction: Ring Of Attraction 1.3.8
		showmeyourskin: Show Me Your Skin! 1.2.1+1.19
		simple_cobblestone_generator: Simple cobblestone generator 1.1.9
		simplevillagers: Simple Villagers 1.4.0
			config2brigadier: Config to Brigadier 1.1.4
			polymer: Polymer (Core) 0.2.2+1.19
				packet_tweaker: Packet Tweaker 0.3.0+1.18.2
				polymer-registry-sync-manipulator: Polymer Registry Sync Manipulator 0.0.1+1.19
			server_translations_api: Server Translations API 1.4.14+1.19-rc2
			sgui: sgui 1.1.1+1.19
		sodium: Sodium 0.4.2+build.16
			org_joml_joml: joml 1.10.4
		stacker: Stacker 3.0.1-1.19.x
		suggestion_tweaker: Suggestion Tweaker 1.19-1.2.1
		techreborn: Tech Reborn 5.3.2
			reborncore: Reborn Core 5.3.2
			team_reborn_energy: Energy 2.2.0
		the_extractinator: The Extractinator 1.10
		toms_storage: Tom's Simple Storage Mod 1.3.5
		torcherino: Torcherino 17.0.1
		trinkets: Trinkets 3.4.0
		universal_ores: Universal Ores 1.4.0
		villager-hats: Villager Hats 1.4.1
		visualoverhaul: VisualOverhaul 4.1.1
		voidtotem: Void Totem 2.0.0
		wildtoolaccess: Wild Tool Access 1.19.0-1.0.1
		wooledboots: Wooled Boots 1.3.1
		zihlaunchpads: ZIHLaunchpads 1.2.0
	Loaded Shaderpack: ComplementaryShaders_v4.5.1.zip
		Profile: Custom (+25 options changed by user)
	Launched Version: 1.19
	Backend library: LWJGL version 3.3.1 SNAPSHOT
	Backend API: NVIDIA GeForce GTX 1080/PCIe/SSE2 GL version 3.2.0 NVIDIA 516.59, NVIDIA Corporation
	Window size: 1920x1080
	GL Caps: Using framebuffer using OpenGL 3.2
	GL debug messages: 
	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fabric'; Server brand changed to 'fabric'
	Type: Integrated Server (map_client.txt)
	Graphics mode: fancy
	Resource Packs: vanilla, Fabric Mods, visualoverhaul/coloredwaterbucket, visualoverhaul/nobrewingbottles, visualoverhaul/fancyfurnace, visualoverhaul/rounddiscs, file/better-rain-1-17, Theinar Language, cullleaves/smartleaves
	Current Language: English (US)
	CPU: 8x AMD Ryzen 5 1500X Quad-Core Processor 
	Server Running: true
	Player Count: 1 / 8; [class_3222['MelonSlayer78'/31, l='ServerLevel[Technolocraft]', x=1972.16, y=113.77, z=-326.61]]
	Data Packs: vanilla, Fabric Mods, dispenser_configurator/default_dispenser_configurators (incompatible), professions/fabric/normal
	World Generation: Experimental

**Comment by IdontPlayz343** [comment]
Omg im a moron, it was an issue with purp
